set(GLFW_SOURCE "${CMAKE_CURRENT_BINARY_DIR}/GLFW")
set(GLFW_INSTALL "${DWARF_EXTERNAL_INSTALL_PREFIX}")

ExternalProject_Add(GLFW
	GIT_REPOSITORY https://github.com/glfw/glfw.git
	GIT_TAG master
	DOWNLOAD_DIR ${DWARF_EXTERNAL_DOWNLOAD}
	PREFIX ${GLFW_SOURCE}
	INSTALL_DIR ${GLFW_INSTALL}
	CMAKE_ARGS
		-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
		-DGLFW_BUILD_DOCS:BOOL=OFF
		-DGLFW_BUILD_EXAMPLES:BOOL=OFF
		-DGLFW_BUILD_TESTS:BOOL=OFF
)
